# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3

# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   <<: *default
#   database: storage/production.sqlite3
#   # For Action Cable (WebSockets) - Use same SQLite DB
#   cable:
#     adapter: sqlite3
#     database: storage/production.sqlite3  # Reuse same file (or use separate if needed)
#     pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#     timeout: 5000

# queue:  # Add this section
#   <<: *default
#   database: storage/production_queue.sqlite3
# PostgreSQL configuration
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: bookapp_development
#   host: 127.0.0.1
#   username: bookapp
#   password: your_password

# test:
#   <<: *default
#   database: bookapp_test
#   host: 127.0.0.1
#   username: bookapp
#   password: your_password

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
#   # Remove host/username/password - use only DATABASE_URL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  username: bookapp
  password: your_password
  database: bookapp_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
