# name: CI

# on:
#   pull_request:
#   push:
#     branches: [ main ]

# jobs:
#   scan_ruby:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version
#           bundler-cache: true

#       - name: Scan for common Rails security vulnerabilities using static analysis
#         run: bin/brakeman --no-pager

#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version
#           bundler-cache: true

#       - name: Lint code for consistent style
#         run: bin/rubocop -f github

#   test:
#     runs-on: ubuntu-latest

#     # services:
#     #  redis:
#     #    image: redis
#     #    ports:
#     #      - 6379:6379
#     #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#       - name: Install packages
#         run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config

#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version
#           bundler-cache: true

#       - name: Run tests
#         env:
#           RAILS_ENV: test
#           # REDIS_URL: redis://localhost:6379/0
#         run: bin/rails db:test:prepare test

name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Security scan
        run: brakeman --no-pager --exit-on-warn

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: RuboCop linting
        run: bundle exec rubocop --format progress --format github

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: [6379:6379]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev
      - name: Set up test database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bookapp_test
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bookapp_test
          RAILS_ENV: test
          REDIS_URL: redis://localhost:6379/0
        run: |
          bundle exec rspec
          bundle exec rails test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [scan_ruby, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify deployment readiness
        run: echo "All tests passed, ready for deployment to Render/Heroku"
        